export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  COMPANY_UNREACHABLE: "COMPANY_UNREACHABLE",
  LLM_RATE_LIMITED: "LLM_RATE_LIMITED",
  LLM_INVALID_RESPONSE: "LLM_INVALID_RESPONSE",
  LLM_UNAVAILABLE: "LLM_UNAVAILABLE",
  KIT_VALIDATION_FAILED: "KIT_VALIDATION_FAILED",
  COVERAGE_INCOMPLETE: "COVERAGE_INCOMPLETE",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
} as const;