export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  COMPANY_UNREACHABLE: "COMPANY_UNREACHABLE",
  LLM_RATE_LIMITED: "LLM_RATE_LIMITED",
  LLM_INVALID_RESPONSE: "LLM_INVALID_RESPONSE",
  KIT_VALIDATION_FAILED: "KIT_VALIDATION_FAILED",
} as const;